# https://github.com/marketplace/actions/github-action-for-firebase
name: Production Firebase Deployment & Lighthouse Audit
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.82.0"
          extended: true
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: hugo --minify --baseURL="https://dailyhealth.app"
      - name: Optimize SVGs
        run: sudo npm install -g svgo && svgo -r ./public
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
          retention-days: 1
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  audit:
    name: Audit
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v3
        with:
          configPath: "./.github/lighthouse/config.json"
          temporaryPublicStorage: true
          urls: |
            https://dailyhealth.app
          runs: 1